---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: prometheus-operator-group
  namespace: monitoring
spec:
  targetNamespaces:
    - monitoring

---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: prometheus-operator
  namespace: monitoring
spec:
  channel: beta
  name: prometheus
  source: operatorhubio-catalog
  sourceNamespace: olm
  installPlanApproval: Automatic