name: Build and Push FreqUI Image

on:
  push:
    branches:
      - main
    paths:
      - 'frequi/**'
      - '.github/workflows/build-frequi.yml'
      - '.github/workflows/_docker-build.yml'
  workflow_dispatch:

concurrency:
  group: build-frequi-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    uses: ./.github/workflows/_docker-build.yml
    with:
      image-name: 'volaticloud-frequi'
      dockerfile: 'frequi/Dockerfile'
      context: './frequi'
      push: true
    permissions:
      contents: read
      packages: write