name: Build and Push Keycloak Image

on:
  push:
    branches:
      - main
      - 'feature/github-actions-*'  # TODO: Remove after testing
    paths:
      - 'keycloak/**'
      - '.github/workflows/build-keycloak.yml'
      - '.github/workflows/_docker-build.yml'
  pull_request:
    branches: [main]
    paths:
      - 'keycloak/**'
      - '.github/workflows/build-keycloak.yml'
      - '.github/workflows/_docker-build.yml'
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/_docker-build.yml
    with:
      image-name: 'volaticloud-keycloak'
      dockerfile: 'keycloak/Dockerfile'
      context: './keycloak'
      push: true
    permissions:
      contents: read
      packages: write