name: Build and Push Docker Image

on:
  push:
    branches:
      - main
    paths:
      - '**.go'
      - 'go.mod'
      - 'go.sum'
      - 'Dockerfile'
      - '.dockerignore'
      - 'internal/**'
      - 'cmd/**'
      - '.github/workflows/docker-build.yml'
      - '.github/workflows/_docker-build.yml'
  pull_request:
    branches: [main]
    paths:
      - 'Dockerfile'
      - '.dockerignore'
      - '.github/workflows/docker-build.yml'
      - '.github/workflows/_docker-build.yml'

jobs:
  build:
    uses: ./.github/workflows/_docker-build.yml
    with:
      image-name: 'volaticloud'
      dockerfile: 'Dockerfile'
      context: '.'
      push: true
    permissions:
      contents: read
      packages: write